### ISSUE TITLE
error: Cannot log after tests are done. Did you forget to wait for something async in your test?

### ISSUE THREAD

**Issue by leedbswo107** [leedbswo107/javascript-baseball-6#4]
- number 에 값이 undefined 상태로 인식 되는점.
- node.js 로 컴파일 하면 실행에는 문제가 없으나.
- npm test 로 테스트 코드 실행시 발생.
- 예상으로는 while 안 while 로 발생하는 문제로 생각되는 부분임

Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TypeError: Cannot read properties of undefined (reading 'length')
        at Validator.length [as validateInputLength] (/Users/leeyunjae/javascript-baseball-6/src/common/Validator.js:6:19)
        at InputView.validateInputLength (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:20:33)
        at call (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:2:1)
        at Generator.tryCatch (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:2:1)
        at Generator._invoke [as next] (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:2:1)
        at asyncGeneratorStep (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:2:1)
        at asyncGeneratorStep (/Users/leeyunjae/javascript-baseball-6/src/view/InputView.js:2:1)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)".

      4 | class Validator{
      5 |     validateInputLength(number) {
    > 6 |         if(number.length !== NUMBERS.three) throw new Error(`${ERROR.invalidNumLength}`); 
        |                   ^
      7 |         console.log('test');
      8 |         console.log(typeof NUMBERS.three);
      9 |         console.log(number.length);

      at Validator.length [as validateInputLength] (src/common/Validator.js:6:19)
      at InputView.validateInputLength (src/view/InputView.js:20:33)
      at call (src/view/InputView.js:2:1)
      at Generator.tryCatch (src/view/InputView.js:2:1)
      at Generator._invoke [as next] (src/view/InputView.js:2:1)
      at asyncGeneratorStep (src/view/InputView.js:2:1)
      at asyncGeneratorStep (src/view/InputView.js:2:1)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)".
      at console.log (node_modules/@jest/console/build/CustomConsole.js:141:10)
      at Function.value (node_modules/@woowacourse/mission-utils/dist/mission-utils.cjs:1:4763)
      at InputView.print (src/view/InputView.js:28:31)
      at call (src/view/InputView.js:2:1)
      at Generator.tryCatch (src/view/InputView.js:2:1)
      at Generator._invoke [as next] (src/view/InputView.js:2:1)
      at asyncGeneratorStep (src/view/InputView.js:2:1)
      at asyncGeneratorStep (src/view/InputView.js:2:1)

**Comment by leedbswo107** [comment]
중첩 while 의 문제로 확인.
try catch 구문은 app.js 에서 한번만 사용하는 것으로 코드 수정완료
